spring.application.name=training-2

spring.datasource.url=jdbc:postgresql://localhost:5432/finance-training-2
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

loan.interest.annual-rate=0.12
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level correlation_id=%X{correlation_id} %logger{36} - %msg%n